version: '3'

services:

  helppoint-mysql:
    container_name: helppoint-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - helppoint-custom-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=helppoint-product

  helppoint-kafka:
    container_name: helppoint-kafka
    build: 
      context: ./kafka/
      dockerfile: ./Dockerfile
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - helppoint-custom-net
    environment:
      - ADVERTISED_HOST=localhost

  helppoint-zipkin:
    container_name: helppoint-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - helppoint-custom-net

  helppoint-configuration-server:
    container_name: helppoint-configuration-server
    build: 
      context: ./helppoint-configuration-server/
      dockerfile: ./Dockerfile
    ports:
      - "9091:9091"
    networks:
      - helppoint-custom-net
    depends_on:
      - helppoint-discovery-server
      - helppoint-zipkin

  helppoint-discovery-server:
    container_name: helppoint-discovery-server
    build: 
      context: ./helppoint-discovery-server/
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - helppoint-custom-net

  helppoint-product:
    container_name: helppoint-product
    build: 
      context: ./helppoint-product/
      dockerfile: ./Dockerfile
    ports:
      - "8092:8092"
    networks:
      - helppoint-custom-net
    depends_on:
      - helppoint-discovery-server
      - helppoint-mysql
      - helppoint-zipkin

  helppoint-client:
    container_name: helppoint-client
    build: 
      context: ./helppoint-client/
      dockerfile: ./Dockerfile
    ports:
      - "8090:8090"
    networks:
      - helppoint-custom-net
    depends_on:
      - helppoint-discovery-server
      - helppoint-mysql
      - helppoint-zipkin

  helppoint-salesman:
    container_name: helppoint-salesman
    build: 
      context: ./helppoint-salesman/
      dockerfile: ./Dockerfile
    ports:
      - "8091:8091"
    networks:
      - helppoint-custom-net
    depends_on:
      - helppoint-discovery-server
      - helppoint-mysql
      - helppoint-zipkin

  helppoint-web:
    container_name: helppoint-web
    image: nginx
    volumes:
      - ./helppoint-web/dist/helppoint-web:/usr/share/nginx/html
    ports:
      - "8080:80"
    depends_on:
      - helppoint-discovery-server
      - helppoint-product

  helppoint-gateway:
    container_name: helppoint-gateway
    build: 
      context: ./helppoint-gateway/
      dockerfile: ./Dockerfile
    ports:
      - "9090:9090"
    networks:
      - helppoint-custom-net
    depends_on:
      - helppoint-discovery-server
      - helppoint-product

networks:
  helppoint-custom-net:
    driver: bridge