version: '3'

services:

  helppoint-mysql:
    container_name: helppoint-mysql
    image: mysql:5.7
    ports:
      - "3306:3306"
    networks:
      - helppoint-custom-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=helppoint-product

  helppoint-kafka:
    container_name: helppoint-kafka
    build: 
      context: ./kafka/
      dockerfile: ./Dockerfile
    ports:
      - "2181:2181"
      - "9092:9092"
    networks:
      - helppoint-custom-net
    environment:
      - ADVERTISED_HOST=localhost

  helppoint-zipkin:
    container_name: helppoint-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"
    networks:
      - helppoint-custom-net

  helppoint-discovery-server:
    container_name: helppoint-discovery-server
    build: 
      context: ./helppoint-discovery-server/
      dockerfile: ./Dockerfile
    ports:
      - "8761:8761"
    networks:
      - helppoint-custom-net

networks:
  helppoint-custom-net:
    driver: bridge